### ISSUE TITLE
Error "maxThumbnailNumber" not found

### ISSUE THREAD

**Issue by MahipalV12** [zangqilong198812/YGCTrimVideoView#1]
![screen shot 2018-01-10 at 6 15 50 pm](https://user-images.githubusercontent.com/28589483/34773622-60a6230a-f632-11e7-8fb8-fdf72e857492.png)

**Comment by zangqilong198812** [comment]
fixed

**Comment by MahipalV12** [comment]
thanks @zangqilong198812 , i need need to use this trimmer in Cell of Tableview.  is trimmer will manage the memory leakage ?

**Comment by MahipalV12** [comment]
and Can you make swift version of this..Please

**Comment by zangqilong198812** [comment]
It generate thumb image only once.so will not make memory leaks

**Comment by zangqilong198812** [comment]
Objective c third party library is easy to use in swift project,why you need swift version?

**Comment by MahipalV12** [comment]
Okay,  thanks a lot :)
