### ISSUE TITLE
叶神,求教以下问题

### ISSUE THREAD

**Issue by ziyouzhe4** [zangqilong198812/YGCTrimVideoView#3]
YGCTrimVideoView.m文件中 316   317行 ,有这几句代码 : 
 CMTime acturalDuraton = CMTimeSubtract(_endTime, _startTime);
 [mutableComposition removeTimeRange:CMTimeRangeMake(acturalDuraton, mutableComposition.duration)];

我不是很明白 获取 AVMutableComposition 时候 为什么要移除 这个timerange 范围的track呢?

**Comment by zangqilong198812** [comment]
你可以注释掉那句话看看结果就明白了。
